/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "H:\\wangyu-web\\vuepress-io\\node_modules\\_@vuepress_core@1.9.8@@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7c7f8174",
    path: "/DevTools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c7f8174").then(next)
    },
  },
  {
    path: "/DevTools/index.html",
    redirect: "/DevTools/"
  },
  {
    name: "v-bdf74bd8",
    path: "/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bdf74bd8").then(next)
    },
  },
  {
    path: "/JavaScript/index.html",
    redirect: "/JavaScript/"
  },
  {
    name: "v-1787c511",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1787c511").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-589a9e18",
    path: "/Note/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-589a9e18").then(next)
    },
  },
  {
    path: "/Note/index.html",
    redirect: "/Note/"
  },
  {
    name: "v-05db55dd",
    path: "/React/project-one.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05db55dd").then(next)
    },
  },
  {
    name: "v-0228291e",
    path: "/React/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0228291e").then(next)
    },
  },
  {
    path: "/React/index.html",
    redirect: "/React/"
  },
  {
    name: "v-45c180d0",
    path: "/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45c180d0").then(next)
    },
  },
  {
    path: "/Vue/index.html",
    redirect: "/Vue/"
  },
  {
    name: "v-7d7d221d",
    path: "/React/project-two.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d7d221d").then(next)
    },
  },
  {
    name: "v-6f51b493",
    path: "/Vue/plugin-two.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f51b493").then(next)
    },
  },
  {
    name: "v-682bd05d",
    path: "/Vue/vue3_source.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-682bd05d").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]