/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "JackyWong's FE",
  "description": "keep moving,toooo!",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "menu",
      "frontmatter": {},
      "regularPath": "/DevTools/",
      "relativePath": "DevTools/readme.md",
      "key": "v-7c7f8174",
      "path": "/DevTools/",
      "headers": [
        {
          "level": 2,
          "title": "menu",
          "slug": "menu"
        }
      ]
    },
    {
      "title": "menu",
      "frontmatter": {},
      "regularPath": "/JavaScript/",
      "relativePath": "JavaScript/readme.md",
      "key": "v-bdf74bd8",
      "path": "/JavaScript/",
      "headers": [
        {
          "level": 2,
          "title": "menu",
          "slug": "menu"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "JackyWong's Front-end",
        "tagline": "开发、学习、笔记",
        "actionText": "GO ->",
        "actionLink": "/JavaScript/",
        "features": [
          {
            "title": "简介",
            "details": "以markdown为中心的项目结构"
          },
          {
            "title": "简介",
            "details": "以markdown为中心的项目结构"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2019-present Jacky Wong"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-1787c511",
      "path": "/"
    },
    {
      "title": "menu",
      "frontmatter": {},
      "regularPath": "/Note/",
      "relativePath": "Note/readme.md",
      "key": "v-589a9e18",
      "path": "/Note/",
      "headers": [
        {
          "level": 2,
          "title": "menu",
          "slug": "menu"
        }
      ]
    },
    {
      "title": "测试代码",
      "frontmatter": {},
      "regularPath": "/React/project-one.html",
      "relativePath": "React/project-one.md",
      "key": "v-05db55dd",
      "path": "/React/project-one.html",
      "headers": [
        {
          "level": 2,
          "title": "测试代码",
          "slug": "测试代码"
        },
        {
          "level": 2,
          "title": "北京",
          "slug": "北京"
        },
        {
          "level": 2,
          "title": "上海",
          "slug": "上海"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/React/",
      "relativePath": "React/README.md",
      "key": "v-0228291e",
      "path": "/React/"
    },
    {
      "title": "仓库地址",
      "frontmatter": {},
      "regularPath": "/Vue/",
      "relativePath": "Vue/README.md",
      "key": "v-45c180d0",
      "path": "/Vue/",
      "headers": [
        {
          "level": 3,
          "title": "仓库地址",
          "slug": "仓库地址"
        }
      ]
    },
    {
      "title": "东京",
      "frontmatter": {},
      "regularPath": "/React/project-two.html",
      "relativePath": "React/project-two.md",
      "key": "v-7d7d221d",
      "path": "/React/project-two.html",
      "headers": [
        {
          "level": 2,
          "title": "东京",
          "slug": "东京"
        }
      ]
    },
    {
      "title": "插件two",
      "frontmatter": {},
      "regularPath": "/Vue/plugin-two.html",
      "relativePath": "Vue/plugin-two.md",
      "key": "v-6f51b493",
      "path": "/Vue/plugin-two.html",
      "headers": [
        {
          "level": 2,
          "title": "插件two",
          "slug": "插件two"
        },
        {
          "level": 2,
          "title": "插件3",
          "slug": "插件3"
        }
      ]
    },
    {
      "title": "1",
      "frontmatter": {
        "sidebarDepth": 2
      },
      "regularPath": "/Vue/vue3_source.html",
      "relativePath": "Vue/vue3_source.md",
      "key": "v-682bd05d",
      "path": "/Vue/vue3_source.html",
      "headers": [
        {
          "level": 2,
          "title": "1",
          "slug": "_1"
        },
        {
          "level": 2,
          "title": "2",
          "slug": "_2"
        },
        {
          "level": 3,
          "title": "2-1",
          "slug": "_2-1"
        },
        {
          "level": 2,
          "title": "3",
          "slug": "_3"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/gratisography-346H.jpg",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "JavaScript",
        "link": "/JavaScript/"
      },
      {
        "text": "Vue",
        "link": "/Vue/"
      },
      {
        "text": "React",
        "link": "/React/"
      },
      {
        "text": "Note",
        "link": "/Note/"
      },
      {
        "text": "DevTools",
        "link": "/DevTools/"
      }
    ],
    "sidebar": {
      "/vue/": [
        [
          "vue3_source",
          "Vue3.0源码学习"
        ],
        [
          "plugin-two",
          "2222222222"
        ]
      ],
      "/react/": [
        [
          "project-one",
          "项目one"
        ],
        [
          "project-two",
          "项目two"
        ]
      ]
    }
  }
}